Repository dhmit/gender_analysis, pull requests merged in 2020-10, with the labels that each got.

#110 Created Test Coverage GitHub Action
  .github/workflows/python-test-coverage.yml
  .travis.yml
Labels: meta

#117 Added Smart Quote Cleaner
  gender_analysis/analysis/dunning.py
  gender_analysis/analysis/gender_frequency.py
  gender_analysis/corpus.py
  gender_analysis/document.py
Labels: bug

#120 Use built-in open() instead of codecs.open
  gender_analysis/common.py
Labels: hacktoberfest-accepted

#123 Created Gender and Pronoun Structures
  gender_analysis/__init__.py
  gender_analysis/common.py
  gender_analysis/gender.py
  gender_analysis/pronouns.py
Labels: enhancement
